version: '3.8'
services:
  frontend:
    build: ./
    container_name: crud_frontend_app
    image: crud-frontend-app
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules

